apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hello-world-app2
spec:
  virtualhost:
    fqdn: hello-world-app2.swa-raj.online
  routes:
    - services:
        - name: hello-world-app2
          port: 80
